### ISSUE TITLE
Split PubSubSubscriberOperations into PubSubSubscriberOperations / PubSubPullerOperations

### ISSUE THREAD

**Issue by dhoard** [spring-cloud/spring-cloud-gcp#873] opened 2018-07-19 12:19 UTC
Related to https://github.com/spring-cloud/spring-cloud-gcp/pull/841 ...

Given some of differences in messages that are returned from the underlying Google library between `GrpcSubscriberStub` for pull and `Subscriber` for subscribe, does it make sense to ...

1. Split `PubSubSubscriberOperations` into `PubSubSubscriberOperations` and 
 `PubSubPullerOperations` ... with associated template classes; message types would be different.

or

2. Remove `subscribe` functionality from `PubSubSubscriberOperations` and recommend Spring Integration for subscription functionality.

or

3. Create a Spring specific `PubSubSubscriber` and `MessageReceiver` that would allow common message types `AcknowledgeablePubSubMessage` / `ConvertedAcknowledgeablePubSubMessage`  to be used `PubSubSubscriberOperations`; this may have to be implemented using `GrpcSubscriberStub` to allow the common message type ... sounds like a partial re-implemention of Spring Integration, but library specific.

or

4. Do nothing / minimal work to resolve https://github.com/spring-cloud/spring-cloud-gcp/pull/841.

<br/>

Thoughts?

**Comment by artembilan** [comment] 2018-07-19 14:06
Well, this is exactly what we do with the `MessageListenerContainer` pattern and appropriate `@...Listener` annotation in other projects:
https://docs.spring.io/spring-kafka/docs/2.1.7.RELEASE/reference/html/_reference.html#kafka-listener-annotation
https://docs.spring.io/spring-amqp/docs/2.0.4.RELEASE/reference/html/_reference.html#async-annotation-driven
https://docs.spring.io/spring/docs/5.0.7.RELEASE/spring-framework-reference/integration.html#jms-annotated

I talked about this in the beginning of the project, but then we really decided that it would be enough to advertise a Spring Integration `MessageDriverChannelAdapter`  appoach, since `@...Listener` really mimics that functionality.

Since we raise the conversion issue not one time and don't see the simple way to handle, I would suggest to start to take a look into the `MessageListenerContainer` solution.

**Comment by meltsufin** [comment] 2018-07-19 14:18
@artembilan The annotation-driven message listeners looks very appealing indeed. However, I think it would be quiet a bit of work to implement. So, I would suggest tracking it as a future enhancement. I'll create an issue for it.

**Comment by meltsufin** [comment] 2018-07-19 14:33
TBH, I'm a bit hesitant to remove the subscribe operations from the template. @saturnism [advocated](https://github.com/spring-cloud/spring-cloud-gcp/pull/148#discussion_r138698263) pretty strongly for it. Although I don't feel very strongly about it, I would just leave it there and still provide more options like the inbound channel adapter, which we already have, and the `@PubSubListener` in the futre.

**Comment by dhoard** [comment] 2018-08-08 19:17
I propose we close this as no plans to implement.

**Comment by artembilan** [comment] 2018-08-08 19:20
Closed as `Works as Designed`.

Thanks for the feedback, @dhoard !

**Closed by artembilan** 2018-08-08 19:20 UTC
Labels: pubsub
