### ISSUE TITLE
Fix exception in spring-cloud-gcp-pubsub-binder-sample

### ISSUE THREAD

**Issue by dmitry-s** [spring-cloud/spring-cloud-gcp#757] opened 2018-06-15 16:04 UTC
When the application starts, I see this exception:

Creating EvaluationContext with no beanFactory

java.lang.RuntimeException: No beanFactory
	at org.springframework.integration.expression.ExpressionUtils.createStandardEvaluationContext(ExpressionUtils.java:85) [spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.cloud.gcp.pubsub.integration.outbound.PubSubMessageHandler.onInit(PubSubMessageHandler.java:251) [spring-cloud-gcp-pubsub-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]

**Comment by artembilan** [comment] 2018-06-15 16:06
Duplicate of #751

**Comment by dmitry-s** [comment] 2018-06-15 16:10
I put the right exception

**Comment by artembilan** [comment] 2018-06-15 16:15
OK. I see now.
Thanks.

The proper fix is to propagate a `BeanFactory` to the `PubSubMessageHandler` created in the `PubSubMessageChannelBinder.createProducerMessageHandler()`

**Closed** 2018-06-18 20:39 UTC
Labels: bug
