### ISSUE TITLE
Datastore stores id as as seperate field

### ISSUE THREAD

**Issue by ormanli** [spring-cloud/spring-cloud-gcp#1713] opened 2019-06-26 10:11 UTC
I am using spring-cloud-gcp-starter-data-datastore:1.1.2.RELEASE. I have a simple object like this
```
@Entity
@Data
public class WishlistLine {
    @Id
    private Long id;
    @Field(name = "item_id")
    private String itemId;
    @Unindexed
    private BigDecimal quantity;
    @Unindexed
    private String comment;
}
```
When I insert a record it stores entities  like this.
```
{
   "__key__":{
      "path":[
         {
            "kind":"WishlistLine",
            "id":"4785074604081152"
         }
      ],
      "partitionId":{
         "namespaceId":"test"
      }
   },
   "id":4785074604081152,
   "item_id":"A",
   "quantity":"1"
}
```

It is duplicating id as another field. I will only prefer to store id under the key.
Is this expected behavior? Is there any way to prevent this?

**Comment by meltsufin** [comment] 2019-06-26 14:43
Duplicate of #1677.
The fix is only available in version `1.2.0.BUILD-SNAPSHOT`.

**Comment by ormanli** [comment] 2019-06-27 11:06
Thanks. What is the estimated release date?

**Comment by meltsufin** [comment] 2019-06-27 14:00
This would be part of the "Hoxton" Spring Cloud release train. The date is currently set to October 17, but can potentially move. The milestones and release candidates will come before then.
See: https://github.com/spring-cloud/spring-cloud-release/milestones

**Closed** 2019-06-27 14:02 UTC
