### ISSUE TITLE
Calls to spanner are hung from java docker

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#969] opened 2018-08-24 22:23 UTC
Hi @meltsufin  @ChengyuanZhao 

iam observing calls to spanner are hung from our concourse build server. i have enabled "DEBUG" on org.springframework.cloud.gcp.data.spanner to get more tracing but of no help. Can you guys let me know if there are any connection timeouts set on spanner and if so why they didnt trigger even aftr 5 mins? 

how do we trace this issue on whats going on ?

[buildlogs.txt](https://github.com/spring-cloud/spring-cloud-gcp/files/2320046/buildlogs.txt)

**Comment by ChengyuanZhao** [comment] 2018-08-26 07:30
@vineela-gampa Are you able to see which specific line the code hangs up on?

**Comment by vineela-gampa** [comment] 2018-08-26 13:37
This is on the build server . We are using concourse for our build . All the tests are run inside a docket container .

It hangs when it’s trying to execute the query or save or update .

**Comment by ChengyuanZhao** [comment] 2018-08-26 16:13
It's difficult to see what could be going on on your server because we do cover these operations thoroughly in our integration tests and see them as working. Are you able to run a simpler sample application using SpannerTemplate in the same environment and see if it hangs at the read/write call?

The Spanner client library's grpc connection settings aren't Spanner-specific, and I do believe there is timeout. I don't have the exact default setting on the top of my mind, but I would be surprised if it's longer than 5 minutes (if even that long).

**Comment by meltsufin** [comment] 2018-08-27 14:15
@vineela-gampa Are you able to connect to other GCP services from the Concourse server?

**Comment by meltsufin** [comment] 2018-08-27 15:08
Duplicate of #966?

**Comment by meltsufin** [comment] 2018-08-28 20:27
@saturnism FYI

@vineela-gampa GRPC doesn't work on Alpine-based docker images and also requires HTTP 2.0.
Can you verify that you Concourse docker images is not based on Alpine? Also, if there is some kind of HTTP proxy between the server and Spanner, it must support HTTP 2.0.

**Comment by vineela-gampa** [comment] 2018-08-28 23:57
@meltsufin  we figured it out. Its purely bcoz the port we expected to have it open was blocked . 

But my request would still remain open as spanner wasnt erroring out and was hung for 5 mins or more. I feel we shouldn have loggers to repor the error.

**Comment by ChengyuanZhao** [comment] 2018-08-29 00:26
Good to hear it has been solved, but I don't think it's appropriate to be detecting and reporting network config issues like a blocked port at the Spring Data Spanner level.

**Closed by ChengyuanZhao** 2018-08-29 00:26 UTC

**Comment by meltsufin** [comment] 2018-08-29 14:06
I guess @vineela-gampa is wondering why Spanner client lib didn't fail faster in this situation, which would cause an exception stack trace to appear to aid debugging. There's probably some very long default connect timeout, but it doesn't seem to be configurable. I asked the question on GCJ: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3616.

**Comment by vineela-gampa** [comment] 2018-08-29 18:12
@meltsufin Yeah you areright. If the connection is leaking i would like to see some stats.
