### ISSUE TITLE
Allow setting content type metadata on file creation using `spring-cloud-gcp-starter-storage`

### ISSUE THREAD

**Issue by jabubake** [spring-cloud/spring-cloud-gcp#194] opened 2017-10-17 14:08 UTC
Currently there is no way to set the metadata for the file to identify the content type when uploading a file to GCS using `spring-cloud-gcp-starter-storage`.

**Comment by artembilan** [comment] 2017-10-19 15:12
I think this is going to be a bit complicated having the fact of simplicity of the high-level `Resource`  abstraction and complexity of the `BlobInfo` object.

I would suggest to consider to do something like `GCSMessageHandler` similar to what we have with the (S)FTP in Spring Integration: https://docs.spring.io/spring-integration/docs/4.3.12.RELEASE/reference/html/ftp.html#ftp-outbound

Otherwise it looks like we would copy/paste the GCP `Storage` service logic into the `GoogleStorageResource`.

Just some other point of view though...

**Comment by joaoandremartins** [comment] 2017-10-19 22:06
@artembilan is your suggestion to write the file to a channel through a Message, setting the content type in a header and then having the GCS channel adapter writing the file in GCS with the correct content type?

If so, then this is a dupe of #34.

**Comment by artembilan** [comment] 2017-10-19 22:30
Yes, that is an idea, @joaoandremartins .
But in addition to the `contentType` we can deal with all other blob properties there, e.g. via the same headers. Or we can just accept a `payload` as a `BlobInfo` instance with all supplied properties.

**Comment by joaoandremartins** [comment] 2017-10-23 16:21
OK, we'll defer this to the work in #34 then. Closing as dupe.

**Closed by joaoandremartins** 2017-10-23 16:21 UTC
