### ISSUE TITLE
Unable to parse id field from an Entity that doesn't explicity has the id as a field on datastore

### ISSUE THREAD

**Issue by lucasoares** [spring-cloud/spring-cloud-gcp#1683] opened 2019-05-14 14:11 UTC
Hello.

I'm facing a issue with the annotated id field which spring can not parse the field and returns it as null.

We are using the version `1.2.0.BUILD-SNAPSHOT` of `spring-cloud-gcp` to use specific features that we need.

My datastore is fully with already existing entities created using the low level api in another language (we are migrating to spring cloud the services that access this database). We can not migrate the write right now so we are creating microservices to read the database first.

In datastore the `id` field doesn't need to be explicity specified as a entity property, it can be used only as an unique id key and because of that all entities doesn't have the id property.

I created this entity class:

```java
@Data
@NoArgsConstructor
@Accessors(chain = true)
@Entity(name = "User")
public class User {
  @Id Long id;

  @Field(name = "created_at")
  Date createdAt;

  String email;

  String name;
  String password;
}
```

Trying to parse the datastore entity to my entity class using the `DatastoreTemplate`, the id field remains `null`. I was looking at the spring code and it only tries to get the field from `id` property. It never tries to get the id field from the key path value.

I think this picture will show what I'm talking about:
![image](https://user-images.githubusercontent.com/10624972/57704860-25266f00-7639-11e9-9d89-43768177c526.png)

The entity doesn't have the `id` property but it has the id value on entity path.

Looking at the code the `EntityPropertyValueProvider` should check if it is an id property (with the method `isId` of `DatastorePersistentProperty`) and if true, it should get the id property from entity path and not from entity property.

OBS.: this debug print was taken from a breakpoint on `DefaultDatastoreEntityConverter` in the method `read`.

**Comment by meltsufin** [comment] 2019-05-14 15:44
Duplicate of #1677?
@ChengyuanZhao Are you working on that one?

**Comment by ChengyuanZhao** [comment] 2019-05-14 15:48
@meltsufin this looks like the same base issue. We don't consider this a bug, but based on the feedback i think it is an improvement worth having. I'll take it on now.

**Closed** 2019-05-15 21:05 UTC
Labels: datastore
