### ISSUE TITLE
Support for Firestore emulator

### ISSUE THREAD

**Issue by mickeyadlg87** [spring-cloud/spring-cloud-gcp#2162] opened 2020-01-31 19:43 UTC
Hello guys,

I just want to know if your spring-cloud-gcp-starter-firestore dependency supports integration with Firestore emulator https://cloud.google.com/sdk/gcloud/reference/beta/emulators/firestore/ , because I was checking your documentation and I wasnt able to find some property to notify application that I need to use firestore emulator

Thanks

**Comment by meltsufin** [comment] 2020-01-31 19:48
I believe we only have support for it in Spring Data Datastore.
@dmitry-s Can it be added for Firestore as well?

**Comment by meltsufin** [comment] 2020-01-31 20:23
Duplicate of #1956.

**Closed by meltsufin** 2020-01-31 20:23 UTC
Labels: firestore, question
