### ISSUE TITLE
Support @CreatedDate for Datastore auditing

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1809] opened 2019-08-12 18:45 UTC
Currently we only support `@LastModifiedDate`, and do not support `@CreatedDate` because it's difficult to know if the entity is being created when saving unless we do a second request to check if that ID already exists. We also cannot rely on the entity ID being NULL, because the users can set the ID for new entities as well.

The proposal is to support `@CreatedDate` based on the NULL ID, and clearly document that it will not work if you set the ID manually.

@Alos

**Comment by elefeint** [comment] 2021-07-15 21:10
Closing as duplicate of GoogleCloudPlatform/spring-cloud-gcp#534

**Closed by elefeint** 2021-07-15 21:10 UTC
Labels: P2, datastore, good first issue
