### ISSUE TITLE
user & password field information missing in the SQL starter ref docs and README.md

### ISSUE THREAD

**Issue by jabubake** [spring-cloud/spring-cloud-gcp#211] opened 2017-10-26 20:23 UTC

**Comment by artembilan** [comment] 2017-10-26 20:33
Not sure what properties you are talking about.
There is a phrase:

> This starter is configured through `DataSourceProperties`.

So, user & password come to the service from there.

Elaborate, please, more what we are missing.

Thanks

**Comment by joaoandremartins** [comment] 2017-10-27 14:30
@artembilan the issue is that it's not well discoverable. We came across the same issue on a hackathon. Thanks for filing, @jabubake 

Btw, happy birthday @artembilan !

**Comment by joaoandremartins** [comment] 2017-11-01 20:48
Fixed by #218.

**Closed by joaoandremartins** 2017-11-01 20:48 UTC
