### ISSUE TITLE
pubsubPublisherThreadPool could not be injected as ThreadPoolTaskScheduler

### ISSUE THREAD

**Issue by MichalNowakowski** [spring-cloud/spring-cloud-gcp#1835] opened 2019-08-27 09:24 UTC
Application fails to start when using GCP Pub/Sub after upgrading Spring Boot and Spring Cloud.

Versions used:
Spring Boot 2.1.7
Spring Cloud Greenwich.SR2
JDK: 11.0.3

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'pubsubPublisherThreadPool' could not be injected as a 'org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler' because it is a JDK dynamic proxy that implements:
	org.springframework.core.task.AsyncListenableTaskExecutor
	org.springframework.scheduling.SchedulingTaskExecutor
	org.springframework.scheduling.TaskScheduler


Action:

Consider injecting the bean as one of its interfaces or forcing the use of CGLib-based proxies by setting proxyTargetClass=true on @EnableAsync and/or @EnableCaching.
```

I have tried with setting proxyTargetClass to true, tried both EnableAsync and EnableCaching.

It only works fine when I manually create the `publisherExecutorProvider` and `subscriberExecutorProvider`:

```
    @Bean
    @ConditionalOnMissingBean(
            name = {"publisherExecutorProvider"}
    )
    public ExecutorProvider publisherExecutorProvider() {
        ThreadPoolTaskScheduler scheduler = new ThreadPoolTaskScheduler();
        scheduler.setPoolSize(this.gcpPubSubProperties.getPublisher().getExecutorThreads());
        scheduler.setThreadNamePrefix("gcp-pubsub-publisher");
        scheduler.initialize();

        return FixedExecutorProvider.create(scheduler.getScheduledExecutor());
    }

    @Bean
    @ConditionalOnMissingBean(
            name = {"subscriberExecutorProvider"}
    )
    public ExecutorProvider subscriberExecutorProvider() {
        ThreadPoolTaskScheduler scheduler = new ThreadPoolTaskScheduler();
        scheduler.setPoolSize(this.gcpPubSubProperties.getPublisher().getExecutorThreads());
        scheduler.setThreadNamePrefix("gcp-pubsub-subscriber");
        scheduler.initialize();

        return FixedExecutorProvider.create(scheduler.getScheduledExecutor());
    }
```

**Comment by MichalNowakowski** [comment] 2019-08-28 13:12
@meltsufin I have also tried with ```spring.aop.proxy-target-class=true```, no difference.


@artembilan this is the piece of code that injects it to the executor providers:

```
    @Bean
    @ConditionalOnMissingBean(
        name = {"publisherExecutorProvider"}
    )
    public ExecutorProvider publisherExecutorProvider(@Qualifier("pubsubPublisherThreadPool") ThreadPoolTaskScheduler scheduler) {
        return FixedExecutorProvider.create(scheduler.getScheduledExecutor());
    }

    @Bean
    @ConditionalOnMissingBean(
        name = {"subscriberExecutorProvider"}
    )
    public ExecutorProvider subscriberExecutorProvider(@Qualifier("pubsubSubscriberThreadPool") ThreadPoolTaskScheduler scheduler) {
        return FixedExecutorProvider.create(scheduler.getScheduledExecutor());
    }
```

It is in spring-cloud-gcp-autoconfigure module in GcpPubSubAutoConfiguration file.

@elefeint: In a simple project created from scratch the problem does not occur. I will try to isolate it and provide you an example.

**Comment by MichalNowakowski** [comment] 2019-08-28 13:21
It seems the reason for the proxy being created is shedlock-spring (https://github.com/lukas-krecan/ShedLock)!

```
        <dependency>
            <groupId>net.javacrumbs.shedlock</groupId>
            <artifactId>shedlock-spring</artifactId>
            <version>2.5.0</version>
        </dependency>
```

Usage:
```
@EnableScheduling
@EnableSchedulerLock
```

After removing the above annotations, the project correctly starts up.

**Comment by MichalNowakowski** [comment] 2019-08-29 12:37
To sum up: shedlock-spring creates a proxy on ThreadPoolTaskScheduler and GCP pub/sub module requires ThreadPoolTaskScheduler.

Solution: Switch shedlock-spring to AOP proxy mode:
```
@EnableSchedulerLock(mode = EnableSchedulerLock.InterceptMode.PROXY_METHOD)
```

Docs: https://github.com/lukas-krecan/ShedLock#scheduled-method-proxy

**Comment by elefeint** [comment] 2019-09-23 20:53
I am going to close this issue, since you've found the root cause.

**Closed by elefeint** 2019-09-23 20:53 UTC
Labels: pubsub
