### ISSUE TITLE
PubSub - PubSubHealthIndicator requires Pub/Sub Viewer permission

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#2380] opened 2020-05-19 23:52 UTC
**Describe the bug**
If a service account is only given Pub/Sub Subscriber or Pub/Sub Publisher permission, but with out the Pub/Sub Viewer permission, then health check will receive Permission Denied error, causing the health check to fail.

I suspect this is because w/o the viewer permission, the service account doesn't have the ability to even pull for any random topic that does not exist.

**Proposal**
Document that the viewer permission is needed. If viewer permission is not granted, then suggest turning it off.

**Comment by elefeint** [comment] 2020-05-20 01:40
Well, that would explain #2374.
But I tested it with subscriber-only role just today, and it worked, so either I messed up my test setup or there is something else going on.

The subscriber role only has three permissions:
* pubsub.snapshots.seek
* pubsub.subscriptions.consume
* pubsub.topics.attachSubscription

**Comment by elefeint** [comment] 2020-05-21 13:29
I can reproduce it now. Closing, as it's a duplicate of #2374.

**Closed by elefeint** 2020-05-21 13:29 UTC
Labels: pubsub
