### ISSUE TITLE
Investigate first-query startup times

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#1250] opened 2018-11-21 17:06 UTC
https://stackoverflow.com/questions/53290938/1st-query-to-spanner-with-spring-is-very-slow

First query time is high. Investigate what part of Spring Data or Spring Data Spanner is causing the initial loading time.

**Comment by meltsufin** [comment] 2019-07-03 20:00
Closing because the OP says that the issue is in Spring Data loading a lot of classes.

**Closed by meltsufin** 2019-07-03 20:00 UTC
Labels: P3, spanner
