### ISSUE TITLE
Exclude spring-gloud-gcp when running integration tests in Gradle

### ISSUE THREAD

**Issue by Smedzlatko** [spring-cloud/spring-cloud-gcp#209] opened 2017-10-26 11:52 UTC
We have a Spring Boot project using spring-cloud-gcp starter for PubSub and I wonder how am I supposed to handle this dependency when running integration tests.

By default, GCP credentials need to be injected into the application. Otherwise, the context will fail to load. I solved this by creating a mocked credentials that are used only during test phase (other profiles use existing credentials) but this reults in runtime exception from this dependency: `io.grpc.StatusRuntimeException: UNAUTHENTICATED`

The tests (not related to PubSub) are running correctly, it is just annoying to see this exception in the logs all the time. I know I can mock PubSub using emulator, but there is no way how to run this emulator from inside the test and I would use it rather for system tests. Is there some easy way how to disable this dependecy for tests only or mock GCP pubsub so it does not throw runtime exception and works offline?

**Comment by meltsufin** [comment] 2017-10-27 02:09
Hi @Smedzlatko. Thank you for submitting the issue. Would you be able to share a sample test that reproduces your setup and the issue? This would help us look for a potential solution. Thanks!

**Comment by Smedzlatko** [comment] 2017-10-27 08:01
@meltsufin Thank you for your response. I think I found an ellegant solution to my problem. Instead of removing the whole dependency when running tests, I can simply make the PubSub configuration bean conditional on certain profiles so it does not appear in my test profile.

Clean new project without PubSub configuration class never fails but as long as certain beans are in the context, it expects working GCP credentials. Turning this bean off solves the problem:

```java
@Configuration
public class PubSubConfig {
}
```

vs

```java
@Configuration
@Profile("!test")
public class PubSubConfig {
}
```

**Comment by joaoandremartins** [comment] 2017-10-27 13:51
Have you tried providing a mock `@Bean` of the Pub/Sub class that requires the credentials?
If you're unit testing, you probably don't want any calls to be made to GCP Pub/Sub.

**Comment by nikartix** [comment] 2018-08-15 07:26
I have the same issue. Which class can I mock to disable pubsub while testing ?
And what is the correct way to make pubsub calls and verifying message sent in the output channel ?

```
@RunWith(SpringRunner::class)
@SpringBootTest
@ActiveProfiles("test")
class InputMessageTranscoderApplicationTests {

    @MockBean
    lateinit var pubsubOutputGateway: PubSubOutboundGateway

    @Mock
    lateinit var ackReplayConsumer: AckReplyConsumer

    @Autowired
    lateinit var messageParser: MessageParser

    @Autowired
    lateinit var inputMessageTranscoder: InputMessageTranscoder

    @Autowired
    @Qualifier("messageReceiver")
    lateinit var messageHandler: MessageHandler

    fun pubsubMessage(payload: String): Message<ByteArray> {
        val headers = HashMap<String, Any>()
        headers[GcpPubSubHeaders.ACKNOWLEDGEMENT] = ackReplayConsumer
        return MessageBuilder.createMessage(payload.toByteArray(),
                MessageHeaders(headers))
    }

    @Test
    fun testMalformedMessageAck() {
        messageHandler.handleMessage(pubsubMessage("HI"))
        verify(ackReplayConsumer, times(1)).ack()
    }

    @Test
    fun testCorrectMessageOutput() {
        val inputMessage = FacebookInputMessage(
                "TYPE",
                arrayOf(
                        Entry("ID_1", 10, arrayOf(
                                Event(
                                        User("SENDER"),
                                        User("RECIPIENT"),
                                        100,
                                        FbMessage("MESSAGE_ID", "MESSAGE_CONTENT"))
                        ))
                )
        )
        val messageJson = messageParser.parseObject(inputMessage)
        val outputMessage = inputMessageTranscoder.transcode(inputMessage)
        val outputMessageJson = messageParser.parseObject(outputMessage)

        messageHandler.handleMessage(pubsubMessage(messageJson))
        verify(ackReplayConsumer, times(1)).ack()
        verify(pubsubOutputGateway, times(1)).sendToPubsub(outputMessageJson)
    }

}

```

This is what I have right now and it's working, but I still need to provide these configurations for tests to run in the first place:

```
spring.cloud.gcp.project-id=project_id
spring.cloud.gcp.pubsub.emulator-host=localhost:8085
```

**Comment by meltsufin** [comment] 2018-08-15 15:44
@dmitry-s Can you please look into this?

**Comment by artembilan** [comment] 2018-08-15 16:46
How about `spring.cloud.gcp.pubsub.enabled = false` application property instead?

This way the whole `GcpPubSubAutoConfiguration` is going to be disabled.

**Comment by nikartix** [comment] 2018-08-16 07:26
Thank you for the reply,
`spring.cloud.gcp.pubsub.enabled = false` actually worked even though Idea warns me about unresolved configuration property.
After setting this property I had another issue as well

```
Parameter 0 of method messageSender in a.l.a.i.config.PubSubConfig required a bean of type 'org.springframework.cloud.gcp.pubsub.core.PubSubOperations' that could not be found.
	- Bean method 'pubSubTemplate' not loaded because @ConditionalOnProperty (spring.cloud.gcp.pubsub.enabled) found different value in property 'spring.cloud.gcp.pubsub.enabled'
```
I resolved this issue by creating `@MockBean` of `PubSubOperations`.
Good thing is I can now use this mocked class to verify pub sub operation, except for that it has 3 methods for publishing and pulling, and don't know which to verify.
Also I can't verify that my message was 'acked' so I still have to use the code above.
But this is definitely an improvement, I don't have to specify `project-id` and `emulator-host` in my test configuration file.

**Comment by nikartix** [comment] 2018-08-16 08:08
I found another solution for to `PubSubOperation` error,
it is
```
@Configuration
@Profile("!test")
class PubSubConfig {
```

**Comment by artembilan** [comment] 2018-08-16 12:38
The `PubSubMessageHandler` uses this merthod from `PubSubOperations`:
```
        /**
	 * Send a message to Pub/Sub.
	 * @param topic   the name of an existing topic
	 * @param payload an object that will be serialized and sent
	 * @return the listenable future of the call
	 */
	<T> ListenableFuture<String> publish(String topic, T payload, Map<String, String> headers);
```

So, I believe this one you should use for stubbing and verifying.

The `AckReplyConsumer` is somehow not related here: it is an *inbound* part, when we consume messages from the Pub/Sub.

I believe we can close the issue now since an original problem is fixed.

**Comment by nikartix** [comment] 2018-08-17 07:48
Yes, we can close this one.

**Closed** 2018-08-17 13:55 UTC
