### ISSUE TITLE
Embedded Id support

### ISSUE THREAD

**Issue by balopat** [spring-cloud/spring-cloud-gcp#588] opened 2018-04-16 21:42 UTC
Provide support for user defined ID classes to capture composite keys.
This would be supported beyond the existing `@PrimaryKey` annotation as an alternative way to map composite keys. Similar to [`@EmbeddedId` ](https://www.objectdb.com/java/jpa/entity/id#Embedded_Primary_Key_) annotation in JPA

**Comment by ChengyuanZhao** [comment] 2018-04-23 22:30
duplicate of #600?

**Comment by balopat** [comment] 2018-04-23 23:36
No, it's not a duplicate, `@EmbeddedId` is different from `@IdClass`. We could decide to drop this one in favor for `@IdClass` though.

**Comment by ChengyuanZhao** [comment] 2018-05-08 15:51
I tried implementing this and I it wouldn't be additional code (and actually we could leave out some extra restrictions and improve reuse of existing code) if we just make it more general and we allow embedding of regular columns and key columns.

**Comment by ChengyuanZhao** [comment] 2018-05-10 19:40
I’m going to do the following unless there are major objections:

- The annotation `@Embedded(keyOrder = x)` is used on properties that are embedded
- Embedded properties must be single items (no lists, sets, collections, etc...)
- The key order in that annotation inserts all of that embedded class’s IDs in this slot in the parent’s key order.
- Embedded classes can have further embedded properties. This is important to have because of the nested parent-child tables in Spanner (a table’s key columns must appear in all children of subsequent generations). This allows users to reuse keys from parent, grandparent, etc.. in siblings and cousins. 
- User cannot access a SpannerPersistentProperty of a property inside an embedded class from the parent class holding the embedded class. He or she can only get or set the entire embedded object. 
- The “flattening” of embedded columns (meaning enumerating all the embedded columns at all levels)  only happens when:
1. Creating the mutation to save to Spanner 
2. Reading from Struct/row from Spanner
3. Getting the key of the object
4. Forming the convention-named queries
5. Forming the DDL for creating the table

**Closed** 2018-07-11 18:47 UTC
Labels: spanner
