### ISSUE TITLE
Support setting CloudSQL project id via application property

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#117] opened 2017-08-21 14:24 UTC
The user should be able to set the project ID of the database instance they're connecting to via `spring.cloud.gcp.sql.projectId=[[PROJECT-ID]]` in application.properties.

**Comment by joaoandremartins** [comment] 2017-08-21 19:57
I think this is a dupe of #107.

This effort should be done across all starters, not just the SQL one.

**Closed by joaoandremartins** 2017-08-21 19:57 UTC
