### ISSUE TITLE
AckMode.AUTO_ACK acks the message even if the processing exception occurs

### ISSUE THREAD

**Issue by radivojen** [spring-cloud/spring-cloud-gcp#2074] opened 2019-12-10 10:31 UTC
From the doc:
The framework acks the PubsubMessage after it is sent to the channel and processed successfully. The framework does not immediately nack the message when the exception occurs, and allows the eventual redelivery to take effect.

The actual behavior:
Processing exception occurs and the message is still acked.

You can see in code that messageNacked = true is only set for AckMode.AUTO and that causes this bug.
`boolean messageNacked = false;

		try {
			sendMessage(getMessageBuilderFactory()
					.withPayload(message.getPayload())
					.copyHeaders(messageHeaders)
					.build());
		}
		catch (RuntimeException re) {
			if (this.ackMode == AckMode.AUTO) {
				message.nack();
				messageNacked = true;
			}
			throw new PubSubException("Sending Spring message failed.", re);
		}
		finally {
			if (!messageNacked && (this.ackMode == AckMode.AUTO || this.ackMode == AckMode.AUTO_ACK)) {
				message.ack();
			}
		}`

**Comment by radivojen** [comment] 2019-12-10 12:35
Also, even without nack, throwing PubSubException causes immediate redelivery by the google pubsub client

**Comment by elefeint** [comment] 2019-12-10 15:01
Thanks for the report! Which mode does your application use -- is it AUTO_ACK?

**Comment by meltsufin** [comment] 2019-12-10 15:20
I believe the bug was introduced in this PR #1951.
@dzou Do you want to take a look?

**Comment by radivojen** [comment] 2019-12-10 15:22
For now doing a POC with AUTO_ACK.
But is as pasted before in PubSubInboundChannelAdapter.
By changing the code like this works as expected:
`catch (RuntimeException re) {
			if (this.ackMode == AckMode.AUTO) {
				message.nack();
			}
			// marking as nacked if processing problem occured
			messageNacked = true;
			// if exception thrown causes immediate redelivery
			//throw new PubSubException("Sending Spring message failed.", re);
		}`

**Comment by dzou** [comment] 2019-12-10 15:26
Yeah let me take a look at this; I remember working on that issue.

**Comment by dzou** [comment] 2019-12-10 21:21
@radivojen - So when running in AUTO_ACK mode, you are proposing we do not throw the PubSubException if an error occurs? (And leave the message not acked nor nacked?)

I just feel that we don't want to swallow the error either though. If we take this approach, should we instead log the error at warn/error level? @elefeint @meltsufin, what are your thoughts?

**Comment by radivojen** [comment] 2019-12-10 21:34
@dzou I'm using this library through spring cloud stream with '@StreamListener' that already logs an error. So this one is redundant for me. Of course, if used as standalone at least warn level logging would be good.

**Comment by elefeint** [comment] 2019-12-10 22:53
There are two issues discussed here; let's split them up:
1) exception causing message to be acked instead of nacked in AUTO_ACK mode: definitely valid issue; we need to fix it.
2) message redelivery when no ack() was sent. This is expected behavior in MANUAL and AUTO_ACK modes -- your default ack deadline will determine how quickly Pub/Sub will attempt to redeliver the message if it did not get an ack.

**Comment by elefeint** [comment] 2019-12-12 18:30
@radivojen For issue (2), you can prevent the exception from bubbling to the client library by providing a Spring Integration error channel. 

Specify the error channel when you create a `PubSubInboundChannelAdapter` bean:
```
adapter.setErrorChannelName("pubsubErrors");
```

And then create the handler on this channel:

```
@ServiceActivator(inputChannel =  "pubsubErrors")
public void pubsubErrorHandler(Message<MessagingException> message) {
	LOGGER.warn("This message is neither acked nor nacked; ack deadline will determine redelivery" + message);
}
```

On our side, we need to at minimum document this better.

**Comment by radivojen** [comment] 2019-12-13 12:03
I already tried with an error channel even before. An exception is no longer in the logs of course, but the redelivery never happens. I waited for more than 10 min which is the maximum ack deadline.

**Comment by elefeint** [comment] 2019-12-13 13:04
That was caused by the acking-instead-of-nacking bug, right? Could you try with the latest snapshot, now that #2075 went in?

**Comment by radivojen** [comment] 2019-12-13 14:05
I tried the latest code and the first issue is fixed of course.
But the problem with error handling still remains. No matter if the PubSubException is thrown if I have the error handler there is no redelivery. Without the error handler and with exception commented out I get the correct behavior.

**Comment by elefeint** [comment] 2019-12-13 15:03
I've re-read the thread, and realized that you are using Spring Cloud Stream. Pub/Sub SCS binder always operates in `AUTO` mode so both acking and nacking are automatic. When you have an error handler, it prevents an exception from bubbling up, causing all messages to be acked. Pub/Sub then assumes they were delivered correctly and does not attempt re-delivery.

I've filed #2079 as a follow up, since customizing `ackMode` is the correct way to fulfill your requirement of allowing ackDeadline to pass before redelivery.

**Comment by radivojen** [comment] 2019-12-13 15:24
That is true. Spring Cloud stream current default is AUTO. But I have already changed the Spring cloud stream myself just to set the AUTO_ACK mode instead (no other changes). And this is the behavior I get. Thank you for filling the ticket since that option will also be very helpful, no to have to override the config.

**Comment by dzou** [comment] 2019-12-13 17:46
I'll pick up #2079 just to finish what we started here.

Just to clarify @radivojen and @elefeint , so is it a satisfactory solution for there to be a way to configure the PubSub inbound channel adapter so that you can specify the ack mode via property? Like through `application.properties`?

**Comment by elefeint** [comment] 2019-12-13 21:27
We might have to revisit throwing that exception in AUTO_ACK and MANUAL modes. @radivojen 's original suggestion of suppressing the exception may be the way to go.

With error handler, the exception is prevented (after all, Spring Integration processed the message successfully), and so we end up acking in the adapter.
If the user throws an exception from message handler, the adapter rethrows it in AUTO_ACK and MANUAL, triggering the client library nacking logic.

**Comment by elefeint** [comment] 2019-12-13 21:37
Because supporting AUTO_ACK and MANUAL modes in the binder is a new feature that we have not previously supported, this does not need to go into SR1.
The bug in spring integration adapter that was acking instead of nacking for AUTO_ACK has been fixed.

@radivojen Are you blocked by the lack of AUTO_ACK support in Pub/Sub SCS binder? We'll determine priority next week.

**Comment by radivojen** [comment] 2019-12-16 09:40
@elefeint supped it up nicely. I'm not blocked since I have overridden the components I need for the proper AUTO_ACK behavior. Of course, once these issues are fixed my code will be much cleaner.

**Comment by dzou** [comment] 2020-03-04 16:16
I think this was resolved by the documentation updates of https://github.com/spring-cloud/spring-cloud-gcp/pull/2103. Let us know if this is still an issue.

**Closed by dzou** 2020-03-04 16:16 UTC
Labels: P1, pubsub

**Comment by elefeint** [comment] 2020-04-01 14:59
The second part of the `PubSubInboundChannelAdapter` issue (pure spring integration, not spring cloud stream related) was never resolved -- the exception propagages up to client library in AUTO_ACK and MANUAL modes, and so the messages that meant to be redelivered after expiry are instead nacked and redelivered immediately.

This is now tracked in #2250.
