### ISSUE TITLE
Web Request Filters are not pushing traceId to Cloud Logging, so log lines are not grouped

### ISSUE THREAD

**Issue by NicolaSpreafico** [spring-cloud/spring-cloud-gcp#2573] opened 2020-11-03 14:42 UTC
Hello,
I found similar issue but no an actual idea or resolution:
- https://github.com/spring-cloud/spring-cloud-sleuth/issues/1666
- https://github.com/spring-cloud/spring-cloud-sleuth/issues/1529
- https://github.com/spring-cloud/spring-cloud-sleuth/issues/1589

I have a Spring Boot Java11 application deployed on GCP App Engine Standard. My goal is to obtain log lines to be grouped under a common parent (the request log), so I can expand them and isolate them across different requests. In order to do so I understood I need to user the logback plugin, so starting from:
- https://cloud.spring.io/spring-cloud-gcp/multi/multi__stackdriver_logging.html
- https://spring-gcp.saturnism.me/app-dev/observability/logging#logback
I implemented the needed configurations
```
<dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-gcp-starter-logging</artifactId>
    </dependency>
```
and the `logback-spring` xml file
```
<configuration>
    <include resource="org/springframework/cloud/gcp/autoconfigure/logging/logback-json-appender.xml" />
  
    <root level="INFO">
      <appender-ref ref="CONSOLE_JSON" />
    </root>
</configuration>
```

As test code I started from the Hello World project: https://cloud.google.com/appengine/docs/standard/java11/quickstart
I add a simple log line in the controller
![image](https://user-images.githubusercontent.com/12278553/97998710-bd468400-1dea-11eb-929b-5dcb264cb130.png)
and it's working
![image](https://user-images.githubusercontent.com/12278553/97998747-ca637300-1dea-11eb-85eb-ab548b3e46e4.png)

The problem here, which is why I'm opening this issue, is that logs generated by Request Filters are logged w/o a traceId, so the Logging Console is not able do group them.

I created 2 very simple filters, just for example, `Filter1` and `Filter2`
```
@Component
public class Filter1 extends OncePerRequestFilter {
    private static final Logger LOG = Logger.getLogger("Filter1");

    @Override
    protected void doFilterInternal(HttpServletRequest arg0, HttpServletResponse arg1, FilterChain arg2)
            throws ServletException, IOException {

        LOG.info("Logger1 preFilter");
        arg2.doFilter(arg0, arg1);
        LOG.info("Logger1 postFilter");

    }
}
```
and I can see the log lines displayed
![image](https://user-images.githubusercontent.com/12278553/97998945-039be300-1deb-11eb-9248-ad26d8fc025f.png)
but because the filter log lines do not have any  traceId, the parent view is not workin
![image](https://user-images.githubusercontent.com/12278553/97999029-1ca49400-1deb-11eb-8ffe-3466ae97fe71.png)

In my actual application I have a couple of actual filters that are providing log lines, and I would like very much to see them under the actual parent request. Is something that can be done? Am I missing some configuration?

**Comment by ttomsu** [comment] 2020-11-03 19:19
My hunch is that there's something up with the filter ordering. I had a sample app handy in the debugger with the latest milestone of Spring Cloud:

![Screenshot from 2020-11-03 14-08-04](https://user-images.githubusercontent.com/13141550/98029987-51f6b500-1dde-11eb-9aa2-c273bb08e83d.png)

You can see that there are 3 relevant filters: `lazyTracingFilter` `myFilter` and `tracingFilter`. The `lazyTracingFilter` delegates calls to the same instance of `tracingFilter`, so the traceId is being set _before_ `myFilter` gets invoked. 

Here is `myFilter`:

```
	@Bean
	public Filter myFilter() {
		return new OncePerRequestFilter() {
			@Override
			protected void doFilterInternal(HttpServletRequest req, HttpServletResponse resp, FilterChain filterChain) throws ServletException, IOException {
				log.info("Trace Before: " + MDC.get(StackdriverTraceConstants.MDC_FIELD_TRACE_ID));
				filterChain.doFilter(req, resp);
			}
		};
	}
```

And the resulting traces in Stackdriver:

![3eBYjKEhatWHyTs](https://user-images.githubusercontent.com/13141550/98030495-17414c80-1ddf-11eb-8584-1f4bb2f4ee83.png)


Can you hit a debug point and peek at your filter config? Does it look anything like mine? If not, what does yours look like?

**Comment by NicolaSpreafico** [comment] 2020-11-04 09:30
Hello,
I added the line you suggested in my filter:
![image](https://user-images.githubusercontent.com/12278553/98092669-37c4e180-1e87-11eb-9e4c-3da9abc1c7a1.png)
(and I removed the Filter2 because for this example 1 filter only is enough, at the end we are talking about the traceId log attribute being missing, 1 or 10 filters, the behaviour is the same.

![image](https://user-images.githubusercontent.com/12278553/98093510-54154e00-1e88-11eb-9edd-81ae666ae32d.png)
In my case I'm getting a `null` so something is missing again.

The application is now very simple, I only have the main class and the filter.
Do you have a working example where you see from Cloud Logging console that log lines generated by filters are actually grouped under the request parent?

**Comment by ttomsu** [comment] 2020-11-04 12:55
Yep - you can find the changes on this commit: https://github.com/ttomsu/spring-cloud-gcp-old/commit/25f24f1a5340cffb2c6fa6b8e8953943ef85cd2b

You can run the sample and/or the test with the following steps:
1. Authenticate: `gcloud auth application-default login`
1. `./mvnw install -DskipTests -T 1C`
1.  Run the application:
    ```
    ./mvnw spring-boot:run --projects spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample/`
    ```
      1. Navigate to `localhost:8080`
      1. Observe trace ID in console
      1. Find trace in the Cloud Console: https://console.cloud.google.com/traces/list?tid=<TRACE_ID_HERE>
1. Run the integration test for the above:
    ```
    ./mvnw verify --projects spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample/ -Dit.trace=true
    ```


Here's what I see in the Cloud Console:

![SUDiPjZdZTmntY6](https://user-images.githubusercontent.com/13141550/98114164-d6931300-1e72-11eb-8e13-78d3eb3b625b.png)
![4waCEBtpicuyiJw](https://user-images.githubusercontent.com/13141550/98114168-d7c44000-1e72-11eb-80a4-c00042e69191.png)

**Comment by NicolaSpreafico** [comment] 2020-11-04 14:18
Hello,
I followed your steps:
1) I downloaded https://github.com/spring-cloud/spring-cloud-gcp/archive/master.zip
2) Opened project `spring-cloud-gcp-master\spring-cloud-gcp-samples\spring-cloud-gcp-trace-sample`
3) Edited the files as your commit (filter implementation, logback xml modifications)

Then I wanted to try directly from online environment, so I deploy the application, with a couple of more changes
4) I disabled the checkstyle plugin which was blocking the deploy
5) I disabled (as suggested) the `CONSOLE` handler in the logback xml
6) I increased the instance up to F2 to avoid memory errors
This is the command I used:
```
$ mvn clean package appengine:deploy -Dapp.deploy.projectId=xxxxx -Dapp.deploy.version=GCLOUD_CONFIG  -DskipTests=true
```

Then I simply hit the `/meet` endpoint and watched logs
![image](https://user-images.githubusercontent.com/12278553/98122375-ca2dab00-1eb0-11eb-9d34-edbe5d5dc269.png)
It seems to be working, I can see the logs from the filter being grouped as well with the parent request.

So what is changed here besides my previous test? Do I need to always enable tracing?
```
# To send 100% of traces to Stackdriver Trace
spring.sleuth.sampler.probability=1.0
```
If so, why this is needed only for Filter logs? W/o this the request logs are working fine.

**Comment by ttomsu** [comment] 2020-11-04 14:51
Yes, the tracing module needs to be added to your `pom.xml` to pick everything up.

Tracing and Logging are separate but related modules - AFAIK you can have one, the other, or both. If you have both, you get some nice features where you can jump from the Trace timing page into the logs that resulted from just that trace (which is the behavior I think you're after).

 The `spring.sleuth.sampler.probability=1.0` property ensures that all records get send to Cloud Trace. By default, only a subset (a sampled portion) of all requests get sent to Trace. After a certain threshold we start charging for the number of traces saved (see https://cloud.google.com/stackdriver/pricing)

I'm glad to see you've got it working! I'm going to close this issue for now, but feel free to reopen if you have more questions.

**Comment by NicolaSpreafico** [comment] 2020-11-04 15:04
Ok thank you.
For my actual case I don't mind about the Cloud Trace functionalities, while I really need to have the request log lines all grouped under the same parent or the logs became unreadable. With the default log configuration, the request log lines are working but somehow the log lines generated in filters are not managed as well.

With this additional configuration the filter log lines are also grouped, so it seems to be a very mandatory configuration for the log part, even if I don't need the Trace part.

**Comment by ttomsu** [comment] 2020-11-04 18:51
Hi @NicolaSpreafico ,

I discussed this with my team a bit more and I think I have a better handler of what's going on - namely that you shouldn't _have_ to add the `trace` module to get the functionality you're looking for.

Background context: When a request is being handled through Spring MVC, it goes through several stages: `Filter` --> `Interceptors` --> Business logic. 

`Filters` are a concept specific to Java Servlets, on which Spring Boot is built.  On the other hand, `Interceptors` are a pure Spring concept. Said another way, `Filters` are deeper in the stack. 

> Note: Spring actually mention in their [Javadocs](https://docs.spring.io/spring-framework/docs/5.3.0-RC1/javadoc-api/org/springframework/web/servlet/HandlerInterceptor.html) about the difference and when you may want to use one or the other.

When you just have the logging module included in your POM, we look for the `x-cloud-trace-context` header (that should be set by either AppEngine or the Google Cloud Load Balancer) using a `HandlerInterceptor` (namely the [`TraceIdLoggingWebMvcInterceptor`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/d1e36d0e6a6db47b6f698dbd2c2f8a878b867467/spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/TraceIdLoggingWebMvcInterceptor.java#L52-L60)). If this value is found, it's stuffed in the MDC for your business logic.

When we add the `trace` module, it activates Spring Sleuth, and _deactivates_ our `TraceIdLoggingWebMvcInterceptor`. Our Cloud Trace integration delegates the same functionality to Spring Sleuth, who implements this logic as a `Filter` (hence the `lazyTracingFilter` and `tracingFilter` filters I pointed you to in my example.) This is why it simply worked out of the box for me - because _I was using the wrong sample application_ - a sample application that had both logging and trace enabled. I'm sorry about that.

I added the same `Filter` to the correct [Logging-only sample application](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/master/spring-cloud-gcp-samples/spring-cloud-gcp-logging-sample/src/main/java/com/example/Application.java) and now see the same thing you do: `com.example.Application - Trace Before: null`

So ultimately you can choose to keep the Trace library added or play with a little Spring bean magic and implement your desired logic as an `Interceptor`. Here's a really simple example that just overrides our existing bean, but that may not work well if you have multiple things you could implement as Interceptors: https://github.com/ttomsu/spring-cloud-gcp/commit/1dfbba3fe826824986a760ec6ab0a2407a800059. Note that this commit goes against the _logging_ sample, not the trace sample.

**Comment by NicolaSpreafico** [comment] 2020-11-05 09:18
Hi @ttomsu,
for the moment I'm keeping the trace plugin with `spring.sleuth.sampler.probability=1.0` as we confirmed being working.

For future improvements I keep record of your suggestion, but right now it's enough as it is.

Thanks

**Comment by NicolaSpreafico** [comment] 2020-11-09 13:14
Hello @ttomsu,
while i'm carrying on with the `Cloud Trace` at `1.0`, I find a different problem.

I have a second filter which manage all uncaught errors, like if I get a nullpointer somewhere or any kind of unmanaged error that need to be logged. I find that when is the case, the actual logs with severe level doesn't contain the trace id

Here is the log with the stacktrace inside the text content, you can see that there is not traceId (it is an illegalargumentexception)
![image](https://user-images.githubusercontent.com/12278553/98545279-89110e80-2295-11eb-8d43-905018d139b3.png)

Is it possible that because the request crashed during execution the component which actually manage the logs has been deactivated?

**Comment by ttomsu** [comment] 2020-11-09 14:09
I'm not sure of the root cause without more knowledge of when the NPE is thrown and what has been processed up to that point. Including the `trace` module actually makes things more complicated since we're delegating to Sleuth to manage the trace context instead of our simpler thread-local variable. 

As a reminder - having Sleuth manage the trace context is separate from the sampler's probability. By setting `spring.sleuth.sampler.probability=1.0` you're ensuring *all* timing data is sent to Cloud Trace - using up CPU/memory resources as well as using up your free tier of Cloud Trace quota.

**Comment by NicolaSpreafico** [comment] 2020-11-09 17:09
A strange behaviour I found.

This is an example to reproduce the scenario I was referring to
```
public static void main(String[] args) {
        SpringApplication.run(SpringbootApplication.class, args);
    }

    @GetMapping("/")
    public String hello() {
        LOG.info("Entering hello Controller");

        throw new IllegalArgumentException("This is an uncaught error");
        // return "Hello world!";
    }

    @Bean
    public Filter myFilter() {
        return new OncePerRequestFilter() {
            @Override
            protected void doFilterInternal(HttpServletRequest req, HttpServletResponse resp, FilterChain filterChain) throws ServletException, IOException {
                LOG.info("Trace Before: " + MDC.get(StackdriverTraceConstants.MDC_FIELD_TRACE_ID));

                try {
                    filterChain.doFilter(req, resp);
                } catch (Exception e) {
                    LOG.info("Filter1 onError");
                    LOG.info("Trace onError: " + MDC.get(StackdriverTraceConstants.MDC_FIELD_TRACE_ID));

                    LOG.log(Level.SEVERE, "Uncaught Error", e);
                    resp.getWriter().print(e.getMessage());
                    resp.setStatus(500);
                    return;
                }

                LOG.info("Filter1 postFilter");
            }
        };
    }
```

```
{"traceId":"5fa976dfdb5904b45df02e650f23f9d5","spanId":"5df02e650f23f9d5","spanExportable":"true","timestampSeconds":1604941535,"timestampNanos":258000000,"severity":"ERROR","thread":"qtp1251133097-24","logger":"SpringbootApplication","message":"Uncaught Error <stacktrace content>","context":"default","logging.googleapis.com/trace":"projects/xxx/traces/5fa976dfdb5904b45df02e650f23f9d5","logging.googleapis.com/spanId":"5df02e650f23f9d5"}
```

And the traceId is actually registered inside the error logs.
The problem I found is that if I declare the filter as an external class, the trace funcionality is not working. Am I missing some Spring configuration?

**Comment by NicolaSpreafico** [comment] 2020-11-11 18:44
@ttomsu I think I was mislead by previous case. In my actual project the problem it isn't that error log are not traced, the problem is that more than 1 filter is not traced at all. I have 3 different filters in my project and only one produces log which actually has trace ids.

In your previous examples did you tried more than 1 filter in order to see if all logs of all filters are actually traced?

**Comment by meltsufin** [comment] 2020-11-18 21:37
@NicolaSpreafico Backtracking a bit, I just want to reiterate what @ttomsu already said about trace ID working without Sleuth. So, if you don't require tracing, you should remove `spring-cloud-gcp-starter-trace`.
The whole trace ID propagation works by setting a thread-local variable, and in the absence of Sleuth, we set this thread-local variable in a Spring Web MVC `HandlerInterceptor`. My understanding is that Servlet filters are always processed before interceptors. So, the trace ID is not set yet set in thread-local when filters are processed.
Consequently, you have two possible ways forward:
1) Replace your servlet filters with Spring MVC interceptors and make sure that they are registered after our `TraceIdLoggingWebMvcInterceptor`.
2) Create a servlet filter version of [TraceIdLoggingWebMvcInterceptor](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-logging/src/main/java/org/springframework/cloud/gcp/logging/TraceIdLoggingWebMvcInterceptor.java), and register it as the first filter in the chain.

**Closed** 2020-11-23 17:29 UTC
Labels: awaiting, question, trace
