### ISSUE TITLE
`DataSourceProperties` should not be changed by `GcpCloudSqlAutoConfiguration`

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-gcp#272] opened 2017-12-15 14:54 UTC
This [@Bean definition](https://github.com/spring-cloud/spring-cloud-gcp/blob/45fc1d415d7eb38ccb5876983a5d5c567283d0af/spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql/src/main/java/org/springframework/cloud/gcp/sql/autoconfig/GcpCloudSqlAutoConfiguration.java#L114) is very suspicious. 

Patching a properties object from another project is a bit fragile and relies on the fact that the auto-configuration will kick-in. Perhaps users may want to get those features even when they are configuring the `DataSource` themselves?

A more standard way of doing this would be to move that logic in an `EnvironmentPostProcessor` (including checking `spring.cloud.gcp.sql.enabled`) and add a `PropertySource` that provides the properties you want to override. 

I also don't think the warning logs are very accurate (you can't log in an `EnvironmentPostProcessor` as the logging system has not been initialized yet).

**Comment by joaoandremartins** [comment] 2017-12-15 15:52
This was discussed to an extent and we abandoned that option because of [this](https://github.com/spring-cloud/spring-cloud-gcp/pull/129#issuecomment-332336469).

Out SQL starter is completely dependent on auto-configuration kicking in. Not sure if I completely understood your point?
If users are configuring the `DataSource` by themselves (e.g., by just using `spring-boot-starter-data-jpa` and not our starter), then it's a conscious decision to have them specify things like jdbc url, class driver name, opening Cloud SQL instance to the internet, etc. etc.

**Comment by snicoll** [comment] 2017-12-15 16:56
> This was discussed to an extent and we abandoned that option because of this.

Good point, I didn't look carefully enough.  

> Out SQL starter is completely dependent on auto-configuration kicking in. 

OK, that doesn't change the fact that injecting the standard `DataSourceProperties` and overriding it with your own copy is not something you should do. It is fragile and even suspicious from an `ApplicationContext` point of view. I don't have a solution to this problem right now but I'd like you to reconsider that pattern.

**Comment by joaoandremartins** [comment] 2017-12-15 20:26
Unfortunately, I also don't know of any other solution for this issue. If one exists and works, I'd be happy to give it a try.
While this might not be a best practice, I haven't come across any scenario where this method fails.

**Comment by snicoll** [comment] 2017-12-16 08:05
I think I have an idea. I'll give it a try and submit a PR if I find it satisfactory.

**Comment by joaoandremartins** [comment] 2018-05-16 14:06
After playing around with an `EnvironmentPostProcessor` for a little while, there are two major hurdles to this solution:
1) Couldn't find a way to make the `EnvironmentPostProcessor` run after the bean generation, not even with `private int order = Ordered.LOWEST_PRECEDENCE;`. The idea would be to inject the `CloudSqlJdbcInfoProvider` created by `GcpCloudSqlAutoConfiguration`.
2) Manually reproduce all those `@ConditionalOnClass()`, etc., in the new `EnvironmentPostProcessor` would look very ugly and complicated.

Seeing as I can't think of any better alternatives, I'll close this issue. We can always revisit if any better alternative comes up.

**Comment by snicoll** [comment] 2018-05-16 14:28
That is disappointing that you close the issue due to a lack of one solution. The original report is still accurate, does that mean you are declining that as an issue?

**Comment by joaoandremartins** [comment] 2018-05-16 14:34
What I don't want is for this issue to linger around forever (zombie issue), which is what will likely happen.

I'm OK to reopen the issue, but we will definitely need to move it out of the RC1 milestone. And probably reduce the priority as well.

**Comment by meltsufin** [comment] 2020-10-05 16:37
@snicoll @artembilan It's been quite a while since this issue was raised, but the topic has come up again recently in https://github.com/spring-cloud/spring-cloud-gcp/issues/2537. It looks like our unsavory trick with `@Primay` is not working anymore. Are there any new option in Spring Boot for accomplishing the same thing?

**Comment by artembilan** [comment] 2020-10-05 17:02
Well, probably the best way is to provide your own `DataSource` bean which is going to override one provided by Spring Boot and could be based on the standard `DataSourceProperties` plus any overrides you need.
Of course with the respective `@AutoConfigureBefore` to mute an out-of-the-box `DataSource` auto-configuration.

**Comment by meltsufin** [comment] 2020-10-05 17:41
The challenge with just providing a `DataSource` bean is that a lot of the Spring Boot configuration is using the `DataSourceProperties` bean directly and would bypass our `DataSource` bean. For example, see `org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration`.

**Comment by artembilan** [comment] 2020-10-05 18:17
And?

Looks like nothing special with that class:
```
 * @author Stephane Nicoll
 */
abstract class DataSourceConfiguration {

	@SuppressWarnings("unchecked")
	protected static <T> T createDataSource(DataSourceProperties properties, Class<? extends DataSource> type) {
		return (T) properties.initializeDataSourceBuilder().type(type).build();
	}

	/**
	 * Tomcat Pool DataSource configuration.
	 */
	@Configuration(proxyBeanMethods = false)
	@ConditionalOnClass(org.apache.tomcat.jdbc.pool.DataSource.class)
	@ConditionalOnMissingBean(DataSource.class)
	@ConditionalOnProperty(name = "spring.datasource.type", havingValue = "org.apache.tomcat.jdbc.pool.DataSource",
			matchIfMissing = true)
	static class Tomcat {
...
```

you probably see that `@ConditionalOnMissingBean(DataSource.class)`. So, as long as you provide your own `DataSource` bean and have an `@AutoConfigureBefore(DataSourceAutoConfiguration.class)` on your auto-configuration , that `DataSourceConfiguration` logic is fully ignored.

You probably could re-use the logic of that class for your own "custom properties" purpose...

**Comment by meltsufin** [comment] 2020-10-05 19:08
Originally, we were trying to re-use the logic in `DataSourceAutoConfiguration` and `DataSourceConfiguration` to allow connection pools and such. And the only way to do it was to not define our own `DataSource` but manipulate the `DataSourceProperties` that these existing configs use. Are you saying we shouldn't rely on `DataSourceConfiguration` to configure the `DataSource` and instead copy its logic to our own auto-config?

**Comment by artembilan** [comment] 2020-10-05 19:11
That's what I would do and look what is going on during development and testing.
Probably we really can reuse some existing code even if it is just copy/paste routine for time being...

Of course, I won't mind if @snicoll shares some his fresh thoughts on the matter including an explanation why `@Primary` doesn't help at the moment.

Thanks

**Comment by snicoll** [comment] 2020-10-06 03:40
> a lot of the Spring Boot configuration is using the DataSourceProperties bean directly

I wouldn't say there's a lot of them. At the end of the day, the auto-configurations that require it are mostly looking at getting the url of the datasource.

> the only way to do it was to not define our own DataSource but manipulate the DataSourceProperties that these existing configs use. 

That's not the only way. We've discussed the `EnvironmentPostProcessor` option. You can't inject beans as this callback is used before the application context is even refreshed. Another option would be to post-process the `DataSourceProperties` bean rather than redeclaring it the way you do. 

I have no idea what could have caused the behaviour change (although I mentioned in my original report the current arrangement is fragile and this could happen). Do you have a small sample I can run to reproduce the problem?

**Comment by meltsufin** [comment] 2020-10-07 19:59
@snicoll Here's a quick repro:

```
$ git clone https://github.com/spring-cloud/spring-cloud-gcp.git

$ cd spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-sql-mysql-sample/

$ echo 'spring.datasource.url=jdbc:h2:mem:none;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE' | cat - src/main/resources/application.properties > src/main/resources/application.properties.new && mv src/main/resources/application.properties.new src/main/resources/application.properties

$ mvn spring-boot:run
```

You should then see an error like this:
```
 nested exception is java.lang.RuntimeException: Driver com.mysql.jdbc.Driver claims to not accept jdbcUrl, jdbc:h2:mem:none;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
```

**Comment by snicoll** [comment] 2020-10-08 11:23
Thanks for the sample.

Yep so the different of behaviour is exactly the kind of subtle difference that I expected when I raised this issue. Here's what happens:

1. Spring Boot creates the regular `DataSourceProperties` bean, it is bound to the environment (as any bean that's a `@ConfigurationProperties`)
2. Spring Cloud GCP injects the bean and mutates it and then expose a `@ConfigurationProperties` bean again
3. Spring Boot bounds this "new bean" to the environment

So the target bean ends up having the updated driver but the URL that has been set in configuration is set again. That's a problem of mutating `DataSourceProperties` rather than the `Environment`.

You may want to try to inject a `ConfigurableEnvironment` and add a `PropertySource` with higher precedence in that method rather. IMO, this should be straightforward. Right now, if you use actuator with a GCP app, you can see an URL to a database in `/actuator/env/spring.datasource.url` that's different than the one the app is actually using. That in itself is a bug to me.

Changing the `Environment` so late isn't great either but as long as it doesn't affect conditions this should work.

**Comment by meltsufin** [comment] 2020-10-15 02:51
@snicoll Thank you for the suggestion about the `ConfigurableEnvironment`.
I was able to modify the existing code to do that, but I wasn't able to get rid of redefining `DataSourceProperties` as it was causing the code that would update the `ConfigurableEnvironment` to run too late despite the `@AutoConfigureBefore(DataSourceAutoConfiguration.class)`. Is there a way to force the update to the `ConfigurableEnvironment` to happen before `DataSourceAutoConfiguration`?
See: #2558.

**Comment by snicoll** [comment] 2020-10-15 07:43
> it was causing the code that would update the ConfigurableEnvironment to run too late despite the @AutoConfigureBefore(DataSourceAutoConfiguration.class).

`@AutoConfigureBefore` is not meant to create the beans themselves but rather to process the bean definitions (the signatures if you will). By annotating your auto-configuration this way, you declare that the bean definitions of this auto-configuration class must be processed before the auto-configuration class you target. This way, conditions such as `@ConditionalOnMissingBean` will be honoured as expected. That doesn't impact when the application context actually calls `@Bean` method to create the bean itself. 

You can mark an explicit runtime dependency by declaring that you need a bean of a certain type. In your case, it's a little bit harder as you want to declare that link in the opposite direction. You could move that code in a bean and declare this link using `AbstractDependsOnBeanFactoryPostProcessor`. See the implementations of that class in our codebase for more details.

Just sharing again that what is happening here is a bit odd and not officially supported by Spring Boot. If you want to use `DataSourceAutoConfiguration` you should modify the `Environment` with the proper callback (`EnvironmentPostProcessor`). I understand you support now a case where the user creates a bean and that impacts how the `DataSource` should be configured. If you can get rid of that, you could also remove this hack.

**Comment by meltsufin** [comment] 2020-11-19 22:22
@snicoll In case you have any feedback, here's the PR in our new repo that follows your suggestion to use `EnvironmentPostProcessor`. https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/131

**Closed** 2020-11-21 01:14 UTC
Labels: P3, backlog, cloud-sql

**Comment by snicoll** [comment] 2020-11-21 09:43
I am so confused. Aren’t we reviewing a code change that uses EnvironmentPostProcessor for this?
