### ISSUE TITLE
Bug - GCS - Signed URL doesn't work in App Engine

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#862] opened 2018-07-14 21:23 UTC
Signed URL seem to work only when a service account was provided.

It doesn't work when:
- using gcloud Application Default Credential on local machine
- when deployed in GAE Standard

```
Signing key was not provided and could not be derived
```

```
2018-07-14 21:20:30.285 ERROR [-,f5bce59075bfb85a7bcbbb60799142d1,b217fbcc91bee489,true] 1 --- [Request3FF4E602] o.s.c.s.i.web.ExceptionLoggingFilter     : Uncaught exception thrown

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: Signing key was not provided and could not be derived
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) ~

...

 2018-07-14 21:20:30.288 ERROR [-,,,] 1 --- [Request3FF4E602] o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/redirect/22ed5fd4-87e4-485d-ab38-0df7e1e58d6d.jpg] due to exception [Signing key was not provided and could not be derived]

java.lang.IllegalStateException: Signing key was not provided and could not be derived
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[guava-20.0.jar:na]
	at com.google.cloud.storage.StorageImpl.signUrl(StorageImpl.java:509) ~[google-cloud-storage-1.35.0.jar:1.35.0]
	at org.springframework.cloud.gcp.storage.GoogleStorageResource.createSignedUrl(GoogleStorageResource.java:183) ~[spring-cloud-gcp-storage-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at com.example.frontend.FrontendController.redirect(FrontendController.java:154) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112-google-v7]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112-google-v7]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112-google-v7]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112-google-v7]
	at ...
```

**Comment by meltsufin** [comment] 2018-08-13 15:54
@saturnism I can't repro this problem with gcloud default creds. Is this still an issue for you?

**Comment by meltsufin** [comment] 2018-08-28 16:00
Closing because unable to reproduce it. Please re-open if the issue sill occurs.

**Closed by meltsufin** 2018-08-28 16:00 UTC
Labels: storage
