### ISSUE TITLE
Failed to mark a promise as failure because it has succeeded already - NoSuchMethodError

### ISSUE THREAD

**Issue by HendPro12** [spring-cloud/spring-cloud-gcp#569] opened 2018-04-12 11:17 UTC
I have followed the messaging-gcp-pubsub getting started guide (https://spring.io/guides/gs/messaging-gcp-pubsub/) and the application successfully publishes messages to my topic.  However, while the application is running it frequently outputs the following to log:

```
WARN 293 --- [-worker-ELG-1-2] i.n.c.AbstractChannelHandlerContext      : Failed to mark a promise as failure because it has succeeded already: DefaultChannelPromise@5555b84b(success)

java.lang.NoSuchMethodError: io.netty.handler.codec.http2.Http2ConnectionEncoder.writePing(Lio/netty/channel/ChannelHandlerContext;ZLio/netty/buffer/ByteBuf;Lio/netty/channel/ChannelPromise;)Lio/netty/channel/ChannelFuture;
        at io.grpc.netty.NettyClientHandler.sendPingFrame(NettyClientHandler.java:568) ~[grpc-netty-1.9.0.jar!/:1.9.0]
        at io.grpc.netty.NettyClientHandler.write(NettyClientHandler.java:287) ~[grpc-netty-1.9.0.jar!/:1.9.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [netty-transport-4.1.23.Final.jar!/:4.1.23.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [netty-transport-4.1.23.Final.jar!/:4.1.23.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) [netty-transport-4.1.23.Final.jar!/:4.1.23.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) [netty-transport-4.1.23.Final.jar!/:4.1.23.Final]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1061) [netty-transport-4.1.23.Final.jar!/:4.1.23.Final]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:295) [netty-transport-4.1.23.Final.jar!/:4.1.23.Final]
        at io.grpc.netty.WriteQueue$AbstractQueuedCommand.run(WriteQueue.java:186) [grpc-netty-1.9.0.jar!/:1.9.0]
        at io.grpc.netty.WriteQueue.flush(WriteQueue.java:124) [grpc-netty-1.9.0.jar!/:1.9.0]
        at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:32) [grpc-netty-1.9.0.jar!/:1.9.0]
        at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:44) [grpc-netty-1.9.0.jar!/:1.9.0]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.23.Final.jar!/:4.1.23.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
```

**Comment by joaoandremartins** [comment] 2018-04-12 14:11
This seems to be a dupe of #555.

Let's get the investigation going there.

**Closed by joaoandremartins** 2018-04-12 14:11 UTC
