### ISSUE TITLE
Calls to spanner are hung from java docker

### ISSUE THREAD

**Issue by srivraokp** [spring-cloud/spring-cloud-gcp#1887] opened 2019-09-13 02:30 UTC
We are having issues in Spring Boot microservice, when app tries to get data from spanner, there is no error in the logs but it just hangs, all other service call which is not connecting to Spanner works fine

This issue is similar to #969 & #1637

The app works fine for a week and then it stops responding for DB calls, we are noticing this in all of our apps which has Spanner inetractions

We are using Hoxton.M2 and Greenwich.SR2 in 2 services respectively and behavior is reproducible in both

**Comment by meltsufin** [comment] 2019-09-13 15:11
I wonder if this could potentially be related to this issue in the client library: https://github.com/googleapis/google-cloud-java/issues/6164.
Have you tried increasing `spring.cloud.gcp.spanner.maxSessions` to see if the app can go longer without hanging? Or, alternatively decreasing the number of sessions to see if the app fails sooner?

Another thing you can try in debugging this, is to set the RPC timeout as described [here](https://github.com/googleapis/google-cloud-java/issues/3616#issuecomment-499420219). You would need to provide your own `Spanner` bean to overwrite the auto-configured one.

Once we have a better understanding of the root cause, we can work on a permanent fix in the library.

Thanks!

**Comment by meltsufin** [comment] 2019-09-13 15:12
cc/ @olavloite in case you have some thoughts on this.

**Comment by olavloite** [comment] 2019-09-13 15:23
This sounds very much like a session leak that builds up over time and in the end will exhaust the session pool. The `SessionPoolOptions` contains the option `setFailIfPoolExhausted`. If you set this for the session pool, a session leak will be easier to detect as you will get an `RESOURCE_EXHAUSTED` error instead of a process that waits indefinitely. Closing the session pool after such an error will also log a stack trace of all the sessions that are still checked out of the pool, giving you a hint about what method is leaking the session.

@meltsufin Is it possible to configure `setFailIfPoolExhausted` in the spring-cloud-gcp-spanner config options?

**Comment by meltsufin** [comment] 2019-09-13 15:43
Thanks @olavloite!
Currently it's not exposed, but one can configure it by providing their own `SessionPoolOptions` bean in the Spring application context.
@srivraokp Can you try this please and report back?

**Comment by srivraokp** [comment] 2019-09-13 17:09
@meltsufin 
Please find below code I did:

@Bean
	public SpannerTransactionManager transactionManager() {
		SessionPoolOptions sessionPoolOptions = SessionPoolOptions.newBuilder()
                .setFailIfPoolExhausted()
                .setMinSessions(1)
                .setMaxSessions(2)
                .build();
		SpannerOptions options = SpannerOptions.newBuilder()
				 .setSessionPoolOption(sessionPoolOptions)
				.build();
		Spanner spanner = options.getService();
		DatabaseId db = DatabaseId.of(options.getProjectId(), spannerInstance, spannerdatabase);
		DatabaseClient dbClient = spanner.getDatabaseClient(db);
		return new SpannerTransactionManager(() -> dbClient);
	}


I have uploaded the Exception, 

[Exception.txt](https://github.com/spring-cloud/spring-cloud-gcp/files/3611066/Exception.txt)

**Comment by olavloite** [comment] 2019-09-13 17:21
@srivraokp Could you share the code that is using the `SpannerTransactionManager`? Could it be that the transaction that your method is returning is never committed or rolled back in your code? That would (as far as I can tell) cause a session leak.

**Comment by srivraokp** [comment] 2019-09-13 17:32
@olavloite 
Please find below code, this is a readonlyTransaction call to get all entities based on a filter

I have attached Service, DAO and repository

[Code.txt](https://github.com/spring-cloud/spring-cloud-gcp/files/3611157/Code.txt)

**Comment by ChengyuanZhao** [comment] 2019-09-13 17:59
@olavloite You're right about why we get the read/write transaction in `doGetTransaction`. Unfortunately Spring doesn't give the detail about if it's read-only until later on in `doBegin`. 
I'm not sure if Spring calls our `doCommit` if the method was annotated as readonly, but I would be really surprised if they didn't (after all how else do we know when to clean up! )

**Comment by srivraokp** [comment] 2019-09-13 19:12
> 
> 
> @srivraokp Thanks, that's clearing up a couple of things.
> 
> @meltsufin I noticed in the `SpannerTransactionManager#doGetTransaction()` method that you are calling `this.databaseClientProvider.get().transactionManager();` on line 82 when a transaction is needed, regardless of the type of transaction (read-only or read/write). In `doBegin()` the `SpannerTransactionManager` checks whether it is is a read-only transaction, and if so, returns a wrapper around the read/write transaction to prevent it from ever writing anything to the database. I assume that you do it like that because it is unknown to the `doGetTransaction()` what kind of transaction the user wants. The `this.databaseClientProvider.get().transactionManager();` will always return a Spanner read/write transaction, and that is inherently a lot less efficient than a read-only transaction. But the most important question in this case is: Do you know if spring-data will explicitly call commit or rollback on a read-only transaction when the method with the `@Transactional(readOnly=true)` annotation has finished? Because if the Spanner `TransactionManager` is not explicitly committed, rolled back or closed, it will leak a session.
> 
> @srivraokp Could you try to execute the same example with a read/write transaction instead of a read-only transaction? (I.e. temporarily remove the readOnly=true from the `@Transactional` annotation)

@olavloite 
just using 	@Transactional is working it is closing the session

**Comment by srivraokp** [comment] 2019-09-13 19:13
@meltsufin 
Can you please let us know in which release will this fix be available

**Comment by ChengyuanZhao** [comment] 2019-09-13 19:16
@meltsufin hmmm this might mean we need to disable read-only access. There is no read-only transaction manager.

**Comment by meltsufin** [comment] 2019-09-13 19:55
From what I can see, `doTransaction()` is only called from `getTransaction(TransactionDefinition definition)`, where the read-only status is already known. It's just that it's not passed into the `doTransaction()` method. We can just abandon using `AbstractPlatformTransactionManager` and implement `PlatformTransactionManager` directly to get around the limitation.

**Comment by ChengyuanZhao** [comment] 2019-09-13 20:12
@meltsufin There's still the challenge of not having a transaction-context that auto-closes without a call to doCommit. When we wrote this (and i think still the case), the only transaction manager the client lib has is read-write.

**Comment by meltsufin** [comment] 2019-09-13 20:13
@ChengyuanZhao Actually, I don't think `doGetTransaction()` should even be creating new transactions. That's the job of `doBegin()`.

**Comment by ChengyuanZhao** [comment] 2019-09-13 20:18
@meltsufin I was under the impression that Spring calls doGetTransaction on our behalf to provide the TransactionObject to doBegin and that there is no way in doBegin to create a transaction and somehow feed it back to the other way for Spring to keep track of.

**Comment by meltsufin** [comment] 2019-09-13 20:35
Looking a bit more into this, for read-only transactions, we create a new transaction that is disconnected from the current transaction context. So, in the `doCommit()` we forget to call `close()` on it.

**Comment by naivegeek** [comment] 2019-09-16 04:08
@ChengyuanZhao @meltsufin @olavloite  we are currently using pubsub, spanner and spring cloud gcp spanner data libraries, our application is using the latest spring boot version 2.1.3.RELEASE and Greenwich.SR1 version for spring cloud release train. We also facing similar issues as above to be specific, spanner 

com.google.cloud.spanner.SpannerException: CANCELLED: io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
at io.grpc.PartialForwardingClientCallListener.onClose (PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose (ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose (ForwardingClientCallListener.java:40)
at com.google.cloud.spanner.spi.v1.SpannerErrorInterceptor$1$1.onClose (SpannerErrorInterceptor.java:100)
at io.grpc.PartialForwardingClientCallListener.onClose (PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose (ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose (ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose (CensusStatsModule.java:678)
at io.grpc.PartialForwardingClientCallListener.onClose (PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose (ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose (ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose (CensusTracingModule.java:397)
at io.grpc.internal.ClientCallImpl.closeObserver (ClientCallImpl.java:459)
at io.grpc.internal.ClientCallImpl.access$300 (ClientCallImpl.java:63)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close (ClientCallImpl.java:546)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600 (ClientCallImpl.java:467)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext (ClientCallImpl.java:531)
at io.grpc.internal.ContextRunnable.run (ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run (SerializingExecutor.java:123)
 Show all

I could open another ticket, but while searching for solutions to my problem I ended up here

**Comment by olavloite** [comment] 2019-09-16 05:14
@naivegeek This is a different problem and not related to this issue.

Based on the above stack trace, it looks like the connection to Cloud Spanner has been closed (i.e. your instance of `com.google.cloud.Spanner` has been closed). Could it be that some other part of your application has already closed it?

**Comment by naivegeek** [comment] 2019-09-16 05:32
@olavloite  sorry, we only started experiencing all this after we upgraded to spring boot version 2.1.3.RELEASE and Greenwich.SR1 version for spring cloud release train.
Thina where much more stable before.

**Comment by meltsufin** [comment] 2019-09-16 13:45
@naivegeek `Greenwich.SR3` is about to be released. Please try `Greenwich.SR2` first, and if you're still having problems, please create a separate issue from this one. Thanks!

**Closed** 2019-09-16 20:21 UTC
Labels: P1, spanner

**Comment by naivegeek** [comment] 2019-09-18 21:25
@meltsufin and @olavloite I will try upgrading to Greenwich.SR2 and see if we have any issues. Thanks for looking into it
