### ISSUE TITLE
[PUBSUB] Message with Attributes are lost in any 1.1.0 release

### ISSUE THREAD

**Issue by ITGuy9401** [spring-cloud/spring-cloud-gcp#1253] opened 2018-11-23 16:19 UTC
In a sample App, if you publish a message without attributes to a topic, the clients attached to the subscriptions will receive it.
In the same App, if you publish a message WITH attributes to a topic, the clients attached to the subscriptions will NOT receive it.

I'm deep diving in that because we need to use 1.1.0, I cannot share any code at the moment, I'll try to make an example case, but it's relatively trivial. 

I've noticed this while moving an app from the `1.0.0.M3` to the `1.1.0.M3` version of Spring Cloud GCP. In `1.0.0.RELEASE` it works.

**Comment by dzou** [comment] 2018-11-26 14:44
Thanks for reporting the issue. I will take a look at this too and see if I can reproduce it locally. Were you trying this out on one of our sample apps or was this one of your own?

**Comment by dzou** [comment] 2018-11-26 21:19
I tried a couple things in our sample apps and wasn't able to replicate the problem. However the things I tried out likely don't match your use case; I'll wait for your input regarding your specific use-case and maybe we can use that to reproduce the problem.

I tried modifying both our pub/sub sample and pub/sub integration sample to attach attributes to messages, both appear to propagate messages successfully.

here are my sample changes:
https://github.com/spring-cloud/spring-cloud-gcp/compare/pubsub-debug?expand=1

**Comment by ITGuy9401** [comment] 2018-11-27 09:53
It's on a private App, I'm trying to create a "shareable" subset of this app, hope this may helps.

Essentially, this is what we have and how they interact. 
In my tests I've used also the GCP Console as starting point for messages.
I'll reply as soon as possible with some code.

```
+---------------+                  +----------------+                   +---------------------+
|               |                  |                |                   |                     |
|               |      PUBSUB      |                |     Send Email    |                     |
|     OAuth2    +------------------>     Mail API   +------------------->      Mail Provider  |
|               |                  |                |                   |                     |
|               |                  |                |                   |                     |
+---------------+                  +----------------+                   +---------------------+
```

**Comment by ITGuy9401** [comment] 2018-11-27 10:54
@dzou this is the source code from my use case. 
I've sent messages from the PUBSUB Console and checked that without attributes, they come instantly, with attributes they don't come.

[test-app.zip](https://github.com/spring-cloud/spring-cloud-gcp/files/2619551/test-app.zip)

**Comment by dzou** [comment] 2018-11-28 15:41
@ITGuy9401 Unfortunately I was still unable to reproduce the issue. I wasn't able to run the code that you sent in the zip file, so I attempted to replicate your pubsub configuration in our [pubsub-integration-sample-receiver app](https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-receiver) and was still able to receive messages that had attributes attached.

Would you be able to modify the [pubsub-integration-sample-receiver app](https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-receiver) to reproduce your issue? It has a very similar configuration to your project; I would imagine that any problem you encounter in your app can be surfaced through this sample.

**Comment by dzou** [comment] 2018-12-17 15:48
Hi again, just wanted to follow up on this - did you make any new findings?

**Comment by dzou** [comment] 2019-01-30 18:36
I will close this issue for now as we were unable to reproduce the issue. However, if the problem still remains please feel free to reopen and provide additional details.

**Closed by dzou** 2019-01-30 18:36 UTC
Labels: pubsub
