### ISSUE TITLE
spanner session timeouts

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#1486] opened 2019-02-27 04:59 UTC
Hi @meltsufin @ChengyuanZhao  we observed an issue where spanner is taking >10s to return data on a query when spanner cpu is above 75%. Is there recommendation to finetune to achieve better performance when we are under high load ?

**Comment by ChengyuanZhao** [comment] 2019-02-27 13:06
@vineela-gampa I've read in the refdocs that when Spanner CPU reaches 75% they say to add another node (though I know that kind of decision may be large or not possible).  Please check with the client library team on their repo for more detail about Spanner's server-side performance.

**Comment by vineela-gampa** [comment] 2019-03-01 04:42
We did add nodes after we saw the issue , didnt he;lp much.

**Comment by ChengyuanZhao** [comment] 2019-03-01 13:53
@vineela-gampa 

I think this one may be a related issue that I fixed last week https://github.com/spring-cloud/spring-cloud-gcp/pull/1476

If you're NOT submitting these queries in a single transaction and all of these queries ARE coming from the same instance spring data spanner on one machine then this issue might be the cause.
(this fix would be in 1.2.0 BUILD SNAPSHOT and 1.1.0 BUILD SNAPSHOT)

**Comment by vineela-gampa** [comment] 2019-03-02 01:38
@ChengyuanZhao  we are not submitting them in a single transaction. They are coming from different compute instances but to one spring data spanner.

**Comment by vineela-gampa** [comment] 2019-03-03 15:36
@ChengyuanZhao we are not using singleUse. Most of our queries are against org.springframework.cloud.gcp.data.spanner.core.SpannerTemplate.query(Class<T>, Statement, SpannerQueryOptions) .Do you think the fix you made part of #1476 needs to be incorporated?

**Comment by vineela-gampa** [comment] 2019-03-03 15:43
![image](https://user-images.githubusercontent.com/2513330/53697543-d8502d80-3d97-11e9-9237-8c30b583c628.png)
Uploading one of the tracing where we observed straight query against a table taking 2000ms sometimes , There is an untraced time of 1,636.258 ms 
Below is the snapshot if it happens in ideal scenario . So something is terribly wrong 
![image](https://user-images.githubusercontent.com/2513330/53697566-0f264380-3d98-11e9-95a7-8e14f5ded266.png)

**Comment by ChengyuanZhao** [comment] 2019-03-03 17:31
@vineela-gampa The fix in #1476 doesn't affect the `query()` method , so I don't think that is the source of the issue.

**Comment by vineela-gampa** [comment] 2019-03-04 04:00
@ChengyuanZhao But i believe something related might be the issue too. If you see intially our response times are around <50ms..
as the load increased  spanner took really long to responsd ..it maxed to 2000ms too. 

![image](https://user-images.githubusercontent.com/2513330/53709796-b2f70a00-3dff-11e9-80c2-eafe1c39d171.png)

**Comment by ChengyuanZhao** [comment] 2019-03-04 13:17
@vineela-gampa I will try to replicate the issue. Is there any detail about the query being run that you might be able to share?

**Comment by vineela-gampa** [comment] 2019-03-04 16:22
@ChengyuanZhao its a straight query to a single table with 2 conditions in where clause (STRING AND INTEGER)

For the first half hr things are good and roughly after half hr looks like it takes >200ms to get the response. Spanner was also not hiking up , i suspect there is a memory leak happening somewhere or read/connection tieouts to spanner grpc calls needs to be adjusted?

![image](https://user-images.githubusercontent.com/2513330/53746640-43b50080-3e67-11e9-88b2-7b9708b13dba.png)

**Comment by vineela-gampa** [comment] 2019-03-05 01:18
@ChengyuanZhao  @meltsufin is there a way we could check if there available connections in the pool or we running out of connections ?

**Comment by ChengyuanZhao** [comment] 2019-03-05 12:52
@vineela-gampa I don't know of a way to get that from the client library, but there is a way to change the allowed number of connections in the pool and then see if that makes a difference. https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/spanner/GcpSpannerProperties.java

**Comment by meltsufin** [comment] 2019-03-05 15:02
@vineela-gampa The best way for us to help you would be to have a sample app that reproduces the issue reliably and we can run ourselves.

**Comment by ChengyuanZhao** [comment] 2019-03-28 17:22
I'm gonna close this issue because this seems to be a query performance question for Spanner. Please feel free to reopen if that is incorrect.

**Closed by ChengyuanZhao** 2019-03-28 17:22 UTC
Labels: question, spanner
