### ISSUE TITLE
Pub/Sub client doesn't reconnect after a permission denied error

### ISSUE THREAD

**Issue by olivierboudet** [spring-cloud/spring-cloud-gcp#2504] opened 2020-08-26 16:04 UTC
**Versions :**
- spring-cloud-gcp:1.2.3.RELEASE
- spring spring-boot:2.3.3.RELEASE

**Is your feature request related to a problem? Please describe.**

When removing the role 'PubSub Subscriber' to the service account used by the application, an expected exception PermissionDeniedException is thrown after few secondes or minutes. Then, if the role is re-added to the service account, the connection is not reopened by the client.

**Steps to reproduce**

1. Start an application listening on a subscription 
2. Remove the role 'PubSub Subscriber' to the service account used by the application
3. Wait for the PermissionDeniedException exception
4. Add the role 'PubSub Subscriber' to the service account used by the application
5. Publish a message in the corresponding topic 

The message is never consumed by the application. It needs to be restarted.

**Describe the solution you'd like**
It could be useful if the client can reconnect after a change in the IAM configuration (errors happens... :) ). I initially thought that the option `keep-alive-interval-minutes: 5` could be used on permission denied error but it has no effect.

**Comment by meltsufin** [comment] 2020-08-27 01:43
We simply delegate to the [Pub/Sub client library](https://github.com/googleapis/java-pubsub) `com.google.cloud.pubsub.v1.Subscriber` to handle the subscription.
So, we probably need to see if the same issue happens when you use that class directly.

**Comment by olivierboudet** [comment] 2020-08-27 12:16
I test it directly with the client library in this sample : https://github.com/olivierboudet/test-pubsub-gcp-issue
Same issue happens so I suppose we can close issue here and I should open it in https://github.com/googleapis/java-pubsub ?

**Comment by meltsufin** [comment] 2020-08-27 15:22
@olivierboudet Yes, please open an issue in `java-pubsub` repo. Many thanks!

**Comment by olivierboudet** [comment] 2020-08-27 15:41
Thanks, I have opened https://github.com/googleapis/java-pubsub/issues/330

**Comment by olivierboudet** [comment] 2021-08-17 08:48
Hello @meltsufin ,
I never took the time to comment here since last year but the issue in `java-pubsub` is closed because they do not consider 403 errors as retryable.
Do you think this is the role of spring-cloud-gcp to handle that or it must be directly in the application code ?

**Comment by meltsufin** [comment] 2021-08-17 14:47
@olivierboudet If it doesn't make sense for the client library to do it, I'm not sure why it would make sense for Spring Cloud GCP. This might be just a requirement relatively unique to your application. In that case, I guess it would make sense to keep in the application code.

**Comment by elefeint** [comment] 2021-08-19 14:57
@olivierboudet If this is a common scenario in your application, you may want to look into defining your own beans with `@RefreshScope`, and refreshing them after a known configuration change or on a regular basis.

Which beans should be `@RefreshScope` depends on your needs. Here is an example using Spring Cloud GCP's Spring Integration support to re-subscribe upon credential refresh: https://github.com/elefeint/examples/tree/master/pubsub-rotate-credentials

**Comment by elefeint** [comment] 2021-08-19 14:57
Closing the issue as working as intended.

**Closed by elefeint** 2021-08-19 14:57 UTC
Labels: pubsub, awaiting-user, P4
